import Head from "next/head";
import Footer from "./Footer";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
    return (
        <div className="flex flex-col min-h-screen">
            <Head>
				<title>Dare2Solve</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/fevicon.png" />
			</Head>
            <Navbar />
            <div className="mt-20 bg-gray-50">
                {children}
            </div>
            <Footer />
        </div>
    );
}

export default Layout;